/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KanbanBoard: typeof import('./src/components/KanbanBoard.vue')['default']
    KanbanCard: typeof import('./src/components/KanbanCard.vue')['default']
    KanbanColumn: typeof import('./src/components/KanbanColumn.vue')['default']
  }
}
